tracer.property: "I AM THE DEFAULT"
tracer.property.test: "I AM THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://localhost:5432/eagle_eye"
#spring.datasource.url: "jdbc:postgresql://db:5432/eagle_eye"
spring.datasource.username: "microuser"
spring.datasource.password: "{cipher}cfa6c171c4b2a4943e80c67e3c586d1d91a7c604cba7d32ae63627b8be0c2f0c"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"

hystrix:
  command.getOrganization.execution.isolation.thread.timeoutInMilliseconds: 10000
  threadpool.orgSrvClient.coreSize: 30
  threadpool.orgSrvClient.maxQueueSize: 10
